const projects=[
{id:1,title:'Academic Staff Union of Universities Complex',location:'Olabisi Onabanjo University, Ago-Iwoye, Ogun State',category:'institutional',categoryLabel:'Institutional',description:'A comprehensive academic union complex presented through site planning, floor plans, roof plan, sections, elevations, schedules, entrance details and three-dimensional views.',slides:[9,10,11,12,13]},
{id:2,title:'Professor Idowu Sobowale International School of Mass Communication',location:'Caleb University, Imota, Lagos State',category:'educational',categoryLabel:'Educational',description:'A multi-level school of communication development documented with floor plans, roof plan, sections, elevations and construction-site photographs.',slides:[14,15,16,17,18]},
{id:3,title:'Commercial Complex',location:'Abeokuta, Ogun State',category:'commercial',categoryLabel:'Commercial',description:'A multi-storey commercial development with site plan, floor plans, sections, elevations, three-dimensional presentation and site photographs.',slides:[19,20,21,22,23]},
{id:4,title:'Caleb International College School Complex',location:'Abijo, Lagos State',category:'educational',categoryLabel:'Educational',description:'A major school complex presented through site planning, multi-floor layouts, roof plan, sections, elevations, entrance view and three-dimensional studies.',slides:[24,25,26,27,28]},
{id:5,title:'Caleb University Cafeteria',location:'Imota, Lagos State',category:'educational',categoryLabel:'Educational',description:'A university cafeteria project documented with its principal floor and roof plans, sections, elevations and three-dimensional views.',slides:[29,30,31,32]},
{id:6,title:'Law College Building Extension',location:'Caleb University, Magodo Campus, Lagos State',category:'educational',categoryLabel:'Educational',description:'A multi-storey extension to the Law College, including site plan, floor plans, roof plan, section and elevations.',slides:[33,34,35]},
{id:7,title:'Hanushi Factory',location:'Sagamu, Ogun State',category:'industrial',categoryLabel:'Industrial',description:'An industrial factory development with extensive site and floor planning, roof plans, sections and multiple elevations.',slides:[36,37,38,39,40,41]},
{id:8,title:'Residential Development I',location:'Abeokuta, Ogun State',category:'residential',categoryLabel:'Residential',description:'A substantial residential development featuring basement, ground and upper-floor plans, roof plan, sections and comprehensive elevations.',slides:[42,43,44,45]},
{id:9,title:'Residential Development II',location:'Abeokuta, Ogun State',category:'residential',categoryLabel:'Residential',description:'A residential scheme with site plan, floor plans, roof plan, sections, elevations and a coordinated gatehouse design.',slides:[46,47,48,49,50]},
{id:10,title:'Residential Development III',location:'Abeokuta, Ogun State',category:'residential',categoryLabel:'Residential',description:'A private residential development documented through site planning, ground and upper-floor layouts, roof plan, sections and elevations.',slides:[51,52,53]},
{id:11,title:'Palace Development',location:'Lagos State',category:'residential',categoryLabel:'Residential / Cultural',description:'A palace development comprising the main building and gatehouse, presented through site plan, floor plans, roof plan, sections and elevations.',slides:[54,55,56,57]}
];
const grid=document.getElementById('projectsGrid'); const modal=document.getElementById('projectModal'); const gallery=document.getElementById('modalGallery'); let activeImages=[],activeIndex=0;
const src=n=>`assets/projects/slide-${String(n).padStart(2,'0')}.jpg`;
function render(filter='all'){grid.innerHTML='';projects.filter(p=>filter==='all'||p.category===filter).forEach(p=>{const a=document.createElement('article');a.className='project-card reveal visible';a.innerHTML=`<div class="project-cover"><img loading="lazy" src="${src(p.slides[p.slides.length-1])}" alt="${p.title}"></div><div class="project-info"><span class="project-tag">${p.categoryLabel}</span><h3>${p.title}</h3><p>${p.location}</p></div>`;a.onclick=()=>openProject(p);grid.appendChild(a)})}
function openProject(p){document.getElementById('modalCategory').textContent=p.categoryLabel;document.getElementById('modalTitle').textContent=p.title;document.getElementById('modalMeta').textContent=p.location;document.getElementById('modalDescription').textContent=p.description;gallery.innerHTML='';activeImages=p.slides.map((n,i)=>({src:src(n),caption:`${p.title} — portfolio sheet ${i+1} of ${p.slides.length}`}));activeImages.forEach((im,i)=>{const f=document.createElement('figure');f.innerHTML=`<img loading="lazy" src="${im.src}" alt="${im.caption}"><figcaption>${im.caption}</figcaption>`;f.onclick=()=>openLightbox(i);gallery.appendChild(f)});modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.classList.add('no-scroll')}
function closeModal(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.classList.remove('no-scroll')}
document.querySelectorAll('[data-close]').forEach(x=>x.onclick=closeModal);
document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');render(b.dataset.filter)});
const lb=document.getElementById('lightbox'),lbImg=document.getElementById('lightboxImage'),lbCap=document.getElementById('lightboxCaption');function openLightbox(i){activeIndex=i;lbImg.src=activeImages[i].src;lbCap.textContent=activeImages[i].caption;lb.classList.add('open');lb.setAttribute('aria-hidden','false')}function closeLightbox(){lb.classList.remove('open');lb.setAttribute('aria-hidden','true')}function move(d){activeIndex=(activeIndex+d+activeImages.length)%activeImages.length;openLightbox(activeIndex)}document.querySelector('.lightbox-close').onclick=closeLightbox;document.querySelector('.lightbox-nav.prev').onclick=()=>move(-1);document.querySelector('.lightbox-nav.next').onclick=()=>move(1);lb.onclick=e=>{if(e.target===lb)closeLightbox()};document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeLightbox();closeModal()}if(lb.classList.contains('open')&&e.key==='ArrowRight')move(1);if(lb.classList.contains('open')&&e.key==='ArrowLeft')move(-1)});
const toggle=document.querySelector('.menu-toggle'),nav=document.querySelector('.main-nav');toggle.onclick=()=>{nav.classList.toggle('open');toggle.setAttribute('aria-expanded',nav.classList.contains('open'))};nav.querySelectorAll('a').forEach(a=>a.onclick=()=>nav.classList.remove('open'));document.getElementById('year').textContent=new Date().getFullYear();const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.1});document.querySelectorAll('.reveal').forEach(e=>io.observe(e));render();
